modLoader="javafml"
loaderVersion="[38,)"
license="All rights reserved"

[[mods]]
modId="spirit"
version="${file.jarVersion}"
displayName="Spirit"
authors="CodexAdrian"
description='''
Some description, fix this @Adrian
'''