modLoader="javafml"
loaderVersion="[41,)"
license="All rights reserved"

[[mods]]
modId="spirit"
version="2.0.0"
displayName="Spirit"
authors="Devs: (Lead) CodexAdrian, Ashh/MsRandom1, ThatGravyBoat, ExpensiveKoala, abused_master/moe/pain in my ass, Artist: Kekie6"
description='''
A Soul Shards inspired mod - Spawn your own mobs with an enhanced mob spawner
'''