modLoader="javafml"
loaderVersion="[38,)"
license="All rights reserved"

[[mods]]
modId="spirit"
version="${file.jarVersion}"
displayName="Spirit"
credits=""
authors="CodexAdrian"
description='''
Some spirity mod TODO cc: @Adrian
'''